# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commented_image',
            new_name='commented_project',
        ),
    ]
